# The namespace to deploy your application
global:
  namespace: hl7validator
frontend1:
  #name is a DNS-1035 label and must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123')
  name: hl7validatorservice
  port: 8080
  replicaCount: 1
  proxy:
    incomingPath: /HL7ValidatorService/
    containerPath: "" # The empty string "" means use same as incomingPath, otherwise the value in the string will replace the value of incomingPath when traffic is sent to the application in the deployed container
  image:
    repository: gt-build.hdap.gatech.edu/hl7validatorservice
    tag: latest
    pullPolicy: Always
#  envFrom:
#    name: omoponfhir3-environment-variables